package reporter

// The normalise rules: rewrite a matching line to a canonical form so the
// dedupe pass collapses its variants. Editing these still means a rebuild;
// the drop rules that used to sit beside them are known_knowns rows now
// (noise-rules.txt, 'knowns seed', ant ADR srg-uHwCr). Estate-identifying
// literals belong in the database via 'knowns add', not here.

type normaliseRule struct {
	pattern     string
	replacement string
}

var normaliseMap = []normaliseRule{
	{`snap-store.+not handling`, "snap-store not handling"},
	{`acvpndownloader_major`, "acvpndownloader_major"},
	{`acvpndownloader_minor`, "acvpndownloader_minor"},
	{`pulseaudio.+segfault`, "pulseaudio segfault"},
	{`setroubleshoot.+SELinux`, "setroubleshoot: SELinux"},
	{`gnome-shell.+DBusError`, "gnome-shell DBusError"},
	{`CCMP.+REPLAY`, "CCMP_REPLAY"},
	{`BA.+FLUSH`, "BA_FLUSH"},
	{`snapd-desktop.+Failed to do gtk init`, "snapd Failed to do gtk init"},
	{`snapd-desktop-integration.+no authorization protocol specified`, "snapd no authorization protocol specified"},
	{`snapd-desktop-integration.+Checking session`, "snapd Checking session"},
	{`snapd-desktop-i.+Forcing a reload`, "snapd Forcing a reload"},
	{`FLUSH.+DEAUTH`, "FLUSH_DEAUTH"},
	{`xs_tcp_setup_socket: connect returned unhandled error`, "xs socket error"},
	{`service=registry`, "docker service=registry"},
	{`snap-store.+not handling`, "snap-store not handling"},
	{`xrdp`, "xrdp"},
	{`puppet-agent.+(Could not|Failed|Unable|failed)`, "puppet-agent Error"},
	{`InRelease`, "InRelease Error"},
	{`audit.+DENIED`, "audit DENIED"},
	{`(acvpnui|acwebhelper|acvpndownloader|acvpnagent)`, "acvpnui (CISCO VPN)"},
	{`puppet.+ensure changed.+corrective`, "puppet ensure changed corrective"},
	{`snap.+store.+error`, "snap-store error"},
	{`systemd.+run-docker-runtime`, "systemd run-docker-runtime"},
	{`Started snap`, "Started snap"},
	{`snap.canonical.*Succeeded`, "snap.canonical Succeeded"},
	{`nagios: wproc:.+early_timeout=1; exited_ok=0; wait_status=0; error_code=62`, "nagios early_timeout"},
	{`kernel:.+ Code: `, "kernel crash or segfault debug info"},
	{`nagios: Warning: Check of host.+timed out`, "nagios host check timed out"},
	{`puppet nagios: wproc.+service=\(null\)`, "puppet service=null"},
	{`nagios:.+read.+ returned error`, "nagios read error"},
	{`nagios:.+wproc:.+early_timeout=1`, "nagios core worker early timeout"},
	{`nagios.+CHECK job .+ timed out`, "nagios check job timed out"},
	{`puppet-agent.+Unable to locate package`, "puppet-agent unable to locate package"},
	{`puppet-agent.+no installation candidate`, "puppet-agent no installation candidate"},
	{`puppet-agent.+returned 100: Reading package lists`, "puppet-agent apt update failed"},
	{`puppet.+Service.+failed dependencies`, "puppet service failed dependencies"},
	{`puppet.+Journal begins at`, "puppet journal begins at"},
	{`puppet.+not available`, "puppet package not available"},
	{`puppet-agent.+No more mirrors to try`, "puppet-agent no more mirrors to try"},
	{`puppet-agent.+Could not retrieve catalog`, "puppet-agent could not retrieve catalog"},
	{`puppet-agent.+Errors were encountered while processing`, "puppet-agent errors encountered while processing"},
	{`puppet-agent.+running.+failed`, "puppet-agent failed to start service on a client"},
	{`sshd.+Connection closed.+preauth`, "sshd connection closed preauth"},
	{`wproc:.+timed out`, "nagios core worker timed out"},
	{`wproc:.+timeout`, "nagios core worker timeout"},
	{`setroubleshoot: SELinux is preventing .+ from .+`, "setroubleshoot SELinux is preventing access (natch)"},
	{`setroubleshoot.+failed to retrieve rpm info`, "setroubleshoot failed to retrieve rpm info"},
	{`/var/run/anydesk.pid`, "anydesk pid file"}, // weird anydesk spam
	{`no free leases`, "dhcp no free leases"},
	{`dhcpd.+DHCPDISCOVER.+via`, "regular dhcpd DHCPDISCOVER"},
	{`pulseaudio segfault`, "pulseaudio segfault"},
	{`nf_conntrack.+full`, "nf_conntrack full"},
	{`snap has no updates available`, "snap has no updates available"},
	{`xs socket error`, "xs socket error"},
	{`puppet-agent Error get lock`, "puppet-agent Error get lock"},
	{`nagios.+check.+timed out`, "nagios check timed out"},
	{`It is held by process`, "It is held by process"},
	{`No Presto metadata`, "puppet No Presto metadata"},
	{`New session.+user root`, "New session user root"},
	{`puppet-agent.+held by process`, "puppet-agent held by process"},
	{`Consecutive tx fail`, "Consecutive tx fail"},
	{`sshd.+from`, "ssh login"},
	{`OnCloseSessionDone error`, "OnCloseSessionDone error"},
	{`UFW BLOCK`, "UFW BLOCK"},
	{`chronyd.+replaced`, "chronyd changed timeserver"},
	{`mtp-probe: checking bus`, "mtp-probe checking bus"},
	{`dhcpd.+is duplicate`, "dhcpd is duplicate"},
	{`smartd.+POWER`, "smartd POWER"},
	{`dhcp6_dump.+No such file or directory`, "dhcp6_dump No such file or directory"},
	{`dhcp_dump.+No such file or directory`, "dhcp_dump No such file or directory"},
	{`dhcpd.+Wrote 0`, "dhcpd Wrote 0 hosts"},
	{`puppet-agent.+ensure`, "puppet-agent ensure"},
	{`Launching IPv4 server only`, "dhcpdLaunching IPv4 server only"},
	{`puppet-agent.+:$`, "puppet-agent empty log line"},
	{`unknown option: denyinterface`, "dhcpd unknown option: denyinterface"},
	{`puppet-agent.+has failures: true`, "puppet-agent has failures: true"},
	// A busy resolver SERVFAILs all day for broken remote zones; keep the
	// fact visible (dedupe caps it at 3 lines) but drop the per-query detail.
	{`named\[\d+\]: client .+ query failed \(SERVFAIL\)`, "named SERVFAIL query failure"},
	{`simplesamlphp.+is now using namespaces`, "simplesamlphp legacy class name deprecation warning"},
}
