package reporter

// Direct port of agents/log_filters.py from the Python original. The three
// lists are meant to be edited per estate; keep entries and order identical
// to the Python file until the parity milestone is signed off.

var ignoreList = []string{
	"Hello recv from server",
	" No entries ",
	"USB disconnect",
	"Is a desktop session",
	"Checking session /org/freedesktop",
	"Loop exited. Forcing reload",
	"onedrive",
	"Finished apt-daily.service",
	"message repeated",
	"CCMP_REPLAY",
	"BA_FLUSH",
	"USB hub found",
	"unknown client",
	"DHCPREQUEST",
	"DHCPACK",
	"DHCPOFFER",
	"Note that yum will try to contact the repo. when it runs most commands",
	"snapd-desktop", // bit brutal, but it spams like hell
	"Starting ISC DHCPv4 server",
	"Internet Systems Consortium DHCP Server",
	"Copyright 2004-2018 Internet Systems Consortium",
	"All rights reserved",
	"Stopping LSB: DHCP server",
	"Dormant child reaped",
	"systemd[1]: Reloading",
	"Cleanup of Temporary Directories",
	"gnome-shell",
	"gdm-x-session",
	"usbmuxd",
	"Starting System Logging Service",
	"Reached target",
	"gsd-media-keys",
	"GNOME",
	"gnome-session-binary",
	"Starting Virtual filesystem",
	"Successfully activated service",
	"Starting Accessibility",
	"Started Path",
	"reused old ethernet address",
	"arpwatch: flip flop",
	"Starting rsyslog.service",
	"tracker-miner-f",
	"tracker-store",
	"Starting Tracker metadata",
	"kubelet",
	"org.freedesktop.ScreenSaver.GetActive",
	"DHCPINFORM",
	"DHCPNAK",
	"Stopped Network Time Synchronization",
	"speech-dispatcher",
	"libreoffice",
	"Message of the Day",
	"treated changed event as add",
	"Logitech",
	" boltd",
	"not supported by any plugin",
	"ipheth",
	"iPhone USB",
}

var regexIgnoreList = []string{
	`Catalog compiled by \S+`,

	`kernel.+hub.+detected`,
	`kernel.+usb.+Product`,
	`(?i)lab.+usb`,
	`kernel:.+\[\s+[0-9]\.[0-9]`,
	`snapd-desktop-i.+Checking session`,
	`snapd-desktop-i.+Forcing a reload.`,
	`puppet-agent.+Requesting catalog from`,
	`puppet.+Building dependency tree`,
	`puppet-agent.+executed successfully`,
	`hid-generic .+ USB HID .+Mouse`,
	`kernel: .+ Keyboard`,
	`kernel: .+ usb.+SerialNumber`,
	`Copyright.+Internet Systems Consortium`,
	`rngd.+stats:`,                                // rngd stats spam
	`ADDRCONF\(NETDEV_UP\): .+ link is not ready`, // IPv6 spam
	`DAD attempt detected for .+ on .+`,           // more IPv6 spam (Duplicate Address Detection)
	`puppet-agent.+Applied catalog in.+seconds`,
	`puppet-agent.+Reading state information`,
	`sshd.+Close session`,
	`lab.+kernel`,
	`lab.+dbus`,
	`lab.+os-prober`,
	`kernel:\s+usb.+(new|New) USB`,
	`kernel:\s+usb.+(removed|Removed|Manufacturer|Product:|SerialNumber|disconnect)`,
	`kernel: .+input:.+HID.+ as `,
	`kernel: .+ KCS in invalid state`, // KCS = Keyboard Controller Style (so says gpt)
	`run-docker-runtime.+Succeeded`,
	`dhcpd.+Server starting service`,
	`x2go.+(succeeded|success)`,
	`dbus.+[Aa]ctiv`,
	`dbus-daemon.+(requested|activated)`,
	`isc-dhcp-server.+Stopping`,
	`systemd.+([Ss]tart|[Rr]each|[Ll]isten|[Ss]topped|[Ss]ucceeded)`,
	`systemd.+GnuPG`,
	`NetworkManager.+(requested_interface_mtu|requested|option|<info>)`,
	`rsyslogd.+(groupid|userid).+changed`,
	`rsyslogd.+(Acquired|start)`,
	`systemd.+Deactivated successfully`,
	`containerd.+(clean|ignoring|loading plugin|disconnected)`,
	`dockerd.+ignoring event`,
	`named.+received from primary`,
	`systemd-logind.+(logged out|Removed session)`,
	`docker.+Succeeded`,
	`snapd-desktop.+theme`,
	`kernel:\s\[\s\s\s+[0-9]`,
	`dnsmasq.+\sread\s`,
	`kernel:.+usb.+(new|New)`,
	`kernel: hub.+(found|attached|detected)`,
	`pcieport.+(bridge|released|assigned)`,
	`firefox.+info`,
	`dockerd.+NetworkDB stats`,
	`enx[0-9a-f]{6}.+renamed`,
	`apt-daily\.service .+ unmet condition check.+ConditionACPower`,
	`For info, please visit.+dhcp`,
	`dhcpd.+Wrote.+ leases to leases file.`,
	`kernel.+usb .+Manufacturer`,
	// ELK-era estate noise (tuned on the 2026-08-26 dump). The anomaly
	// detectors run on the RAW lines upstream of this filter, so volume
	// changes in any of these still get flagged; this only keeps them
	// away from the LLM issue path.
	`named\[\d+\]: client .+ denied`,                   // scanners probing an authoritative DNS box
	`named\[\d+\]: client .+ query failed \(REFUSED\)`, // the REFUSED twin of every denied line
	`named\[\d+\]: .*rate limit (slip|drop)`,           // response-rate-limiting doing its job
	`CROND?\[\d+\]: \([^)]+\) (CMD|LIST)`,              // cron ran a job / listed a crontab
	`CRON.+No MTA installed`,
	`crontab\[\d+\]: \([^)]+\) LIST`,
	`dhclient\[\d+\]: XMT: Solicit`, // DHCPv6 solicit heartbeat
	`ocsinventory-agent.+\[debug\]`,
	`puppet-agent.+Testing connection with`, // Defender connectivity self-check
	`systemd.+Closed `,
	`systemd-logind.+New session`,
	`Got notification message from PID`, // mdatp systemd notify chatter
	`nfsrahead.+setting .+ readahead`,
	`named\[\d+\]: (stop limiting|limit REFUSED) error responses`, // RRL start/stop announcements
	`systemd\[\d+\]: .+ Consumed .*CPU time`,                      // per-service resource accounting
	`nessus-service.+Killing nessusd`,                             // nessus agent's scheduled restart
	`rpc\.mountd.+client (attached|detached)`,                     // routine NFS mounts
}

type normaliseRule struct {
	pattern     string
	replacement string
}

var normaliseMap = []normaliseRule{
	{`snap-store.+not handling`, "snap-store not handling"},
	{`acvpndownloader_major`, "acvpndownloader_major"},
	{`acvpndownloader_minor`, "acvpndownloader_minor"},
	{`pulseaudio.+segfault`, "pulseaudio segfault"},
	{`setroubleshoot.+SELinux`, "setroubleshoot: SELinux"},
	{`gnome-shell.+DBusError`, "gnome-shell DBusError"},
	{`CCMP.+REPLAY`, "CCMP_REPLAY"},
	{`BA.+FLUSH`, "BA_FLUSH"},
	{`snapd-desktop.+Failed to do gtk init`, "snapd Failed to do gtk init"},
	{`snapd-desktop-integration.+no authorization protocol specified`, "snapd no authorization protocol specified"},
	{`snapd-desktop-integration.+Checking session`, "snapd Checking session"},
	{`snapd-desktop-i.+Forcing a reload`, "snapd Forcing a reload"},
	{`FLUSH.+DEAUTH`, "FLUSH_DEAUTH"},
	{`xs_tcp_setup_socket: connect returned unhandled error`, "xs socket error"},
	{`service=registry`, "docker service=registry"},
	{`snap-store.+not handling`, "snap-store not handling"},
	{`xrdp`, "xrdp"},
	{`puppet-agent.+(Could not|Failed|Unable|failed)`, "puppet-agent Error"},
	{`InRelease`, "InRelease Error"},
	{`audit.+DENIED`, "audit DENIED"},
	{`(acvpnui|acwebhelper|acvpndownloader|acvpnagent)`, "acvpnui (CISCO VPN)"},
	{`puppet.+ensure changed.+corrective`, "puppet ensure changed corrective"},
	{`snap.+store.+error`, "snap-store error"},
	{`systemd.+run-docker-runtime`, "systemd run-docker-runtime"},
	{`Started snap`, "Started snap"},
	{`snap.canonical.*Succeeded`, "snap.canonical Succeeded"},
	{`nagios: wproc:.+early_timeout=1; exited_ok=0; wait_status=0; error_code=62`, "nagios early_timeout"},
	{`kernel:.+ Code: `, "kernel crash or segfault debug info"},
	{`nagios: Warning: Check of host.+timed out`, "nagios host check timed out"},
	{`puppet nagios: wproc.+service=\(null\)`, "puppet service=null"},
	{`nagios:.+read.+ returned error`, "nagios read error"},
	{`nagios:.+wproc:.+early_timeout=1`, "nagios core worker early timeout"},
	{`nagios.+CHECK job .+ timed out`, "nagios check job timed out"},
	{`puppet-agent.+Unable to locate package`, "puppet-agent unable to locate package"},
	{`puppet-agent.+no installation candidate`, "puppet-agent no installation candidate"},
	{`puppet-agent.+returned 100: Reading package lists`, "puppet-agent apt update failed"},
	{`puppet.+Service.+failed dependencies`, "puppet service failed dependencies"},
	{`puppet.+Journal begins at`, "puppet journal begins at"},
	{`puppet.+not available`, "puppet package not available"},
	{`puppet-agent.+No more mirrors to try`, "puppet-agent no more mirrors to try"},
	{`puppet-agent.+Could not retrieve catalog`, "puppet-agent could not retrieve catalog"},
	{`puppet-agent.+Errors were encountered while processing`, "puppet-agent errors encountered while processing"},
	{`puppet-agent.+running.+failed`, "puppet-agent failed to start service on a client"},
	{`sshd.+Connection closed.+preauth`, "sshd connection closed preauth"},
	{`wproc:.+timed out`, "nagios core worker timed out"},
	{`wproc:.+timeout`, "nagios core worker timeout"},
	{`setroubleshoot: SELinux is preventing .+ from .+`, "setroubleshoot SELinux is preventing access (natch)"},
	{`setroubleshoot.+failed to retrieve rpm info`, "setroubleshoot failed to retrieve rpm info"},
	{`/var/run/anydesk.pid`, "anydesk pid file"}, // weird anydesk spam
	{`no free leases`, "dhcp no free leases"},
	{`dhcpd.+DHCPDISCOVER.+via`, "regular dhcpd DHCPDISCOVER"},
	{`pulseaudio segfault`, "pulseaudio segfault"},
	{`nf_conntrack.+full`, "nf_conntrack full"},
	{`snap has no updates available`, "snap has no updates available"},
	{`xs socket error`, "xs socket error"},
	{`puppet-agent Error get lock`, "puppet-agent Error get lock"},
	{`nagios.+check.+timed out`, "nagios check timed out"},
	{`It is held by process`, "It is held by process"},
	{`No Presto metadata`, "puppet No Presto metadata"},
	{`New session.+user root`, "New session user root"},
	{`puppet-agent.+held by process`, "puppet-agent held by process"},
	{`Consecutive tx fail`, "Consecutive tx fail"},
	{`sshd.+from`, "ssh login"},
	{`OnCloseSessionDone error`, "OnCloseSessionDone error"},
	{`UFW BLOCK`, "UFW BLOCK"},
	{`chronyd.+replaced`, "chronyd changed timeserver"},
	{`mtp-probe: checking bus`, "mtp-probe checking bus"},
	{`dhcpd.+is duplicate`, "dhcpd is duplicate"},
	{`smartd.+POWER`, "smartd POWER"},
	{`dhcp6_dump.+No such file or directory`, "dhcp6_dump No such file or directory"},
	{`dhcp_dump.+No such file or directory`, "dhcp_dump No such file or directory"},
	{`dhcpd.+Wrote 0`, "dhcpd Wrote 0 hosts"},
	{`puppet-agent.+ensure`, "puppet-agent ensure"},
	{`Launching IPv4 server only`, "dhcpdLaunching IPv4 server only"},
	{`puppet-agent.+:$`, "puppet-agent empty log line"},
	{`unknown option: denyinterface`, "dhcpd unknown option: denyinterface"},
	{`puppet-agent.+has failures: true`, "puppet-agent has failures: true"},
	// A busy resolver SERVFAILs all day for broken remote zones; keep the
	// fact visible (dedupe caps it at 3 lines) but drop the per-query detail.
	{`named\[\d+\]: client .+ query failed \(SERVFAIL\)`, "named SERVFAIL query failure"},
	{`simplesamlphp.+is now using namespaces`, "simplesamlphp legacy class name deprecation warning"},
}
